### ISSUE TITLE
Communicate with Howard and Steven to see how I need to post images to get back processed images.

### ISSUE THREAD

**Issue by MattGuptil** [HL232/bme590final#53]
YUP

**Comment by MattGuptil** [comment]
Let me know please, tyty.

**Comment by AznStevy** [comment]
This will be the general workflow (slightly different). First, on your side, the user uploads 1 or many images, and you need to make an `/api/process/upload_image` which would need to contain something like what is shown below. It can be a dict or a list of dicts like that, in the event you are uploading multiple images. You will receive back an image object of the last one that is uploaded, just for confirmation.
```
[
    { 
        "filename": "test",
        "user_id": "myemail@gmail.com or something",
        "image_data": "base 64 image"
    },
    { 
        "filename": "test",
        "user_id": "myemail@gmail.com or something",
        "image_data": "base 64 image"
    }
]
```
Next, I assume you have a list of photos that the user can choose from... if the user clicks an image, you will need to send me the `user_id` and `image_id` so that i can set the current image on the server side. That object will look something like this:
```
    { 
        "user_id": "myemail@gmail.com or something",
        "image_id": "id that you stored on your side."
    }
```
Then you can start doing the processing on THAT image. This means you can make posts such as `/api/process/blur`, which will give you back a blurred image. If you don't like it, you can send another post with something like `/api/process/sharpen`. All of these will require you to send the `user_id`. EVERY TIME THE USER CHANGES IMAGES, YOU NEED TO MAKE A CHANGE POST! 
```
    { 
        "user_id": "myemail@gmail.com or something"
    }
```
NEXT, if you like the change and want to confirm, you need to use the `/api/process/confirm` which also only takes a `user_id`. This will process the change and set that image to the user's current image (internally). You can continue this step as much as you want. There are additional endpoints such as `/api/process/previous_image` and `/api/process/next_image` which allow you to move internally. All of these will return to you a dict with all the info.

DOWNLOADING: If you just want all the user's updated images that they processed or didn't, use the `/api/user/get_updated_uploads/<user_id>` get endpoint; this again requires a user_id. To get a specific list of images, you can use the `/api/image/get_images/` endpoint which takes the user_id and a list of the image_ids you wish to get.

```
    { 
        "user_id": "myemail@gmail.com or something",
        "image_ids": ["ID1", "ID2"]
    }
```
I don't know how downloading really works on your end.

**Comment by suyashkumar** [comment]
https://stackoverflow.com/a/9463806

**Comment by AznStevy** [comment]
I we're ok with the headers now
